CREATE TABLE `학과` (
	`DEPARTMENT_NO`	VARCHAR2(10)	NOT NULL	COMMENT '학과 번호',
	`DEPARTMENT_NAME`	VARCHAR2(20)	NOT NULL	COMMENT '학과 이름',
	`Field`	VARCHAR2(20)	NULL	COMMENT '계열',
	`OPNE_YN`	CHAR(1)	NULL	COMMENT '개설 여부',
	`CAPACITY`	NUMBER	NULL	COMMENT '정원'
);

CREATE TABLE `과목` (
	`CLASS_NO`	VARCHAR2(10)	NOT NULL	COMMENT '과목 번호',
	`DEPARTMENT_NO2`	VARCHAR2(10)	NOT NULL	COMMENT '학과 번호',
	`CLASS_NAME`	VARCHAR2(30)	NOT NULL	COMMENT '과목 이름',
	`CLASS_TYPE`	VARCHAR2(10)	NULL	COMMENT '과목 구분',
	`PREATTENDING_CLASS_NO`	VARCHAR2(10)	NULL	COMMENT '과목 번호'
);

CREATE TABLE `교수` (
	`PROFESSOR_NO`	VARCHAR2(10)	NOT NULL	COMMENT '교수 번호',
	`DEPARTMENT_NO`	VARCHAR2(10)	NOT NULL	COMMENT '학과 번호',
	`PROFESSOR_NAME`	VARCHAR2(30)	NOT NULL	COMMENT '교수 이름',
	`PROFESSOR_SSN`	VARCHAR2(14)	NULL	COMMENT '교수 주민번호',
	`PROFESSOR_ADDRESS`	VARCHAR2(100)	NULL	COMMENT '교수 주소'
);

CREATE TABLE `학생` (
	`STUDENT_NO`	VARCHAR2(10)	NOT NULL,
	`DEPARTMENT_NO`	VARCHAR2(10)	NOT NULL	COMMENT '학과 번호',
	`PROFESSOR_NO`	VARCHAR2(10)	NOT NULL	COMMENT '교수 번호',
	`STUDENT_NAME`	VARCHAR2(30)	NOT NULL,
	`STUDENT_SSN`	VARCHAR2(14)	NULL,
	`STUDENT_ADDRESS`	VARCHAR2(100)	NULL,
	`ENTRANCE_DATE`	DATE	NULL,
	`ABSENCE_YN`	CHAR(1)	NULL	DEFAULT N
);

CREATE TABLE `과목 교수` (
	`CLASS_NO`	VARCHAR2(10)	NOT NULL	COMMENT '과목 번호',
	`PROFESSOR_NO`	VARCHAR2(10)	NOT NULL	COMMENT '교수 번호'
);

CREATE TABLE `성적` (
	`TERM_NO`	VARCHAR2(10)	NOT NULL,
	`CLASS_NO`	VARCHAR2(10)	NOT NULL	COMMENT '과목 번호',
	`STUDENT_NO`	VARCHAR2(10)	NOT NULL,
	`POINT`	NUMBER(3,2)	NULL
);

ALTER TABLE `학과` ADD CONSTRAINT `PK_학과` PRIMARY KEY (
	`DEPARTMENT_NO`
);

ALTER TABLE `과목` ADD CONSTRAINT `PK_과목` PRIMARY KEY (
	`CLASS_NO`,
	`DEPARTMENT_NO2`
);

ALTER TABLE `교수` ADD CONSTRAINT `PK_교수` PRIMARY KEY (
	`PROFESSOR_NO`,
	`DEPARTMENT_NO`
);

ALTER TABLE `학생` ADD CONSTRAINT `PK_학생` PRIMARY KEY (
	`STUDENT_NO`,
	`DEPARTMENT_NO`,
	`PROFESSOR_NO`
);

ALTER TABLE `과목 교수` ADD CONSTRAINT `PK_과목 교수` PRIMARY KEY (
	`CLASS_NO`,
	`PROFESSOR_NO`
);

ALTER TABLE `성적` ADD CONSTRAINT `PK_성적` PRIMARY KEY (
	`TERM_NO`,
	`CLASS_NO`,
	`STUDENT_NO`
);

ALTER TABLE `과목` ADD CONSTRAINT `FK_학과_TO_과목_1` FOREIGN KEY (
	`DEPARTMENT_NO2`
)
REFERENCES `학과` (
	`DEPARTMENT_NO`
);

ALTER TABLE `교수` ADD CONSTRAINT `FK_학과_TO_교수_1` FOREIGN KEY (
	`DEPARTMENT_NO`
)
REFERENCES `학과` (
	`DEPARTMENT_NO`
);

ALTER TABLE `학생` ADD CONSTRAINT `FK_학과_TO_학생_1` FOREIGN KEY (
	`DEPARTMENT_NO`
)
REFERENCES `학과` (
	`DEPARTMENT_NO`
);

ALTER TABLE `학생` ADD CONSTRAINT `FK_교수_TO_학생_1` FOREIGN KEY (
	`PROFESSOR_NO`
)
REFERENCES `교수` (
	`PROFESSOR_NO`
);

ALTER TABLE `과목 교수` ADD CONSTRAINT `FK_과목_TO_과목 교수_1` FOREIGN KEY (
	`CLASS_NO`
)
REFERENCES `과목` (
	`CLASS_NO`
);

ALTER TABLE `과목 교수` ADD CONSTRAINT `FK_교수_TO_과목 교수_1` FOREIGN KEY (
	`PROFESSOR_NO`
)
REFERENCES `교수` (
	`PROFESSOR_NO`
);

ALTER TABLE `성적` ADD CONSTRAINT `FK_과목_TO_성적_1` FOREIGN KEY (
	`CLASS_NO`
)
REFERENCES `과목` (
	`CLASS_NO`
);

ALTER TABLE `성적` ADD CONSTRAINT `FK_학생_TO_성적_1` FOREIGN KEY (
	`STUDENT_NO`
)
REFERENCES `학생` (
	`STUDENT_NO`
);

